### ISSUE TITLE
Integrate WMS data

### ISSUE THREAD

**Issue by domist07** [cgre-aachen/gemgis#1]
**Is your feature request related to a problem? Please describe.**
If you doesn't have a DTM of your area you could get it from a WMS service in the internet or you could expand your information by overlaying the DTM with a topographic/geological map.

**Describe the solution you'd like**
Add and cut WMS data to the study area and colouring the DTM simply by inserting a WMS-link to a function.

![grafik](https://user-images.githubusercontent.com/59735059/81571056-baba2300-93a1-11ea-8ee8-b0e2faf47950.png)
Blue points are boreholes ([Picture source](https://britishgeologicalsurvey.github.io/Groundhog/user.html#importing-exporting-data))

**Comment by AlexanderJuestel** [comment]
@domist07 

I have prepared a little notebook which illustrates how to load a WebMapService and how to convert the image into a Numpy array for further usage. Just go through and let me know if you have any comments on that so that we may improve it.

https://github.com/cgre-aachen/gemgis/blob/development_gemgis_alex_juestel/notebooks/WMS_GemGIS.ipynb

**Comment by domist07** [comment]
Thank you @AlexanderJuestel for the great tutorial!
It works pretty good 😊. Only at the end it will be usefull inserting a comment, that you have rescaled and tranfered your coordinates to zero. When I try to insert my data points I was wondering why they aren't on the map.

**Comment by AlexanderJuestel** [comment]
Yes, I think what I forgot was project the array to the original coordinates as we commonly do in GemPy. Thanks for the hint and I will fix it :) 

Feel free to add any other ideas that come into your mind :)
