### ISSUE TITLE
How do gempy and gemgis combine? 

### ISSUE THREAD

**Issue by liujunyi** [cgre-aachen/gemgis#181]
**What is your question?**
How do gempy and gemgis combine? Can gemgis use gempy models to other data formats?
gempy is python 3.7, gemgis use python 3.9,can use same python environment?

**Comment by AlexanderJuestel** [comment]
Hey @liujunyi, 

thanks for your interest in GemGIS! The purpose of GemGIS currently is to simplify the data processing of spatial data that can then be used to create a GemPy model. In addition, we provide some small post processing tools to visualize single surfaces for instance. 

For a detailed installation guide, please have a look at https://gemgis.readthedocs.io/en/latest/getting_started/installation.html. 
GemPy was working there with Python 3.9 as well. 

However, since Pyvista was updated recently, you may want to fix the PyVista Version to 0.29 and some of the minor releases (0.29.3 or 4 I guess). A PR has already been submitted to fix this issue on the GemPy side: https://github.com/cgre-aachen/gempy/pull/611

Please reach out if you have any further questions!

Cheers 
Alex

**Comment by AlexanderJuestel** [comment]
Hello @liujunyi 

I will close this issue as no new questions have come up from your side so far. Feel free to open the issue again if necessary!

Cheers 
Alex
