### ISSUE TITLE
suggestion: replace wms with gdal native support using rasterio

### ISSUE THREAD

**Issue by AndrewAnnex** [cgre-aachen/gemgis#70]
to simplify the code a bit, gemgis could use the native capability within gdal to read WMS using rasterio

https://gdal.org/drivers/raster/wms.html
https://gis.stackexchange.com/questions/294056/reading-a-wms-raster-map-with-rasterio

**Comment by AlexanderJuestel** [comment]
Hey @AndrewAnnex, 

thanks for your tip. Do you know by chance if rasterio can also handle WFS and WCS services? I tried getting them to run with OWSLib but have failed so far. Only a manual request let me download some WCS data (see misc notebooks). 

Otherwise, this will be something to look into if we could get rid of the OWSLib dependency this way!
Cheers Alex

**Comment by AndrewAnnex** [comment]
Geopandas might be able to work with wfs As that is a vector data type, but I did not find a good example on stack exchange, although the underlying OGR library does support it. Maybe in time this functionality will be exposed by geopandas. WCS is for raster data, so rasterio should also support it. 

-Andrew Annex

**Comment by AlexanderJuestel** [comment]
@AndrewAnnex sorry for the late reply. I had a look at the issue on stackexchange again. Even if you use rasterio, you would have to specify the bounding box etc. So we somehow need to pass these arguments anyways. However, with the current transitioning of the GemPy topography module to GemGIS, we could use that as an opportunity to go full rasterio at least for the WMS services. And if we can make WCS services work with rasterio, it would be even better :)

**Comment by AlexanderJuestel** [comment]
Issue will be closed for now
